version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - graylog-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    networks:
      - graylog-net

  graylog:
    image: graylog/graylog:4.1
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=hashedpassword
      - GRAYLOG_HTTP_EXTERNAL_URI=http://192.168.1.253:9000/
    networks:
      - graylog-net
    ports:
      - "9000:9000"
      - "12201:12201"
      - "1514:1514"
    depends_on:
      - mongo
      - elasticsearch

networks:
  graylog-net:
    driver: bridge
